# Generated by Django 3.2.7 on 2021-09-09 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True)),
                ('buy_in', models.FloatField()),
                ('prize_for_first', models.FloatField()),
                ('prize_for_second', models.FloatField()),
                ('prize_for_third', models.FloatField()),
                ('date', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('eighth_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='eighth_place', to='players.player')),
                ('fifth_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fifth_place', to='players.player')),
                ('first_place', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='first_place', to='players.player')),
                ('fourth_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fourth_place', to='players.player')),
                ('ninth_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ninth_place', to='players.player')),
                ('second_place', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='second_place', to='players.player')),
                ('seventh_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='seventh_place', to='players.player')),
                ('sixth_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sixth_place', to='players.player')),
                ('third_place', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='third_place', to='players.player')),
            ],
        ),
    ]
