# Generated by Django 3.2.7 on 2021-09-08 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True)),
                ('second_place', models.IntegerField()),
                ('third_place', models.IntegerField()),
                ('fourth_place', models.IntegerField(blank=True, null=True)),
                ('fifth_place', models.IntegerField(blank=True, null=True)),
                ('sixth_place', models.IntegerField(blank=True, null=True)),
                ('seventh_place', models.IntegerField(blank=True, null=True)),
                ('eight_place', models.IntegerField(blank=True, null=True)),
                ('ninth_place', models.IntegerField(blank=True, null=True)),
                ('buy_in', models.FloatField()),
                ('prize_for_first', models.FloatField()),
                ('prize_for_second', models.FloatField()),
                ('prize_for_third', models.FloatField()),
                ('date', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('first_place', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='players.player')),
            ],
        ),
    ]
