# Generated by Django 3.2.7 on 2021-09-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='number_of_players',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
