# Generated by Django 3.2.7 on 2021-09-08 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
        ('games', '0002_alter_game_first_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='second_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='players.player'),
        ),
    ]
