# Generated by Django 3.2.7 on 2021-09-23 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_player_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='user_Id',
            new_name='user_id',
        ),
    ]
